name: Run notebook monthly

on:
  schedule:
    - cron: "0 9 1 * *"       # at 09:00 UTC on the 1st day of every month
  workflow_dispatch:          # allows manual run via GitHub Actions tab

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papermill jupyter
          pip install requests pandas python-dateutil

      # Option A: Directly execute notebook
      #- name: Execute notebook with papermill
      #  run: |
      #   papermill notebooks/your.ipynb notebooks/your-output.ipynb

      # Option B: Use your .py script (uncomment and comment the step above)
      - name: Execute with Python runner script
        run: python fetch_transaction.py

      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: AddressTransaction
          path: outputs/
